import Core
import Foundation
import WhisperShared

enum ErrorLocalization {
    static func message(for error: Error, language: AppLanguage) -> String {
        if let error = error as? AIServiceError {
            return aiMessage(error, language: language)
        }
        if let error = error as? ClaudeError {
            return claudeMessage(error, language: language)
        }
        if let error = error as? ParakeetEngineError {
            return parakeetMessage(error, language: language)
        }
        if let error = error as? IOSAudioEngineError {
            return audioMessage(error, language: language)
        }
        return error.localizedDescription
    }

    /// Streaming runs currently retain a display string. Recognize every
    /// message generated by Core so it can still follow the in-app language.
    static func message(forStoredMessage message: String, language: AppLanguage) -> String {
        if message == "Geannuleerd." {
            return L10n.string( "Geannuleerd.", locale: language.locale)
        }
        for provider in AIProvider.allCases {
            let candidates: [AIServiceError] = [
                .missingKey(provider), .invalidKey(provider), .rateLimited(provider),
                .insufficientCredit(provider), .network(provider), .timeout(provider),
                .invalidResponse(provider),
            ]
            if let match = candidates.first(where: { $0.localizedDescription == message }) {
                return aiMessage(match, language: language)
            }
            let prefix = "\(provider.displayName) gaf een fout: "
            if message.hasPrefix(prefix) {
                return aiMessage(
                    .server(provider, String(message.dropFirst(prefix.count))),
                    language: language
                )
            }
        }
        return message
    }

    private static func aiMessage(_ error: AIServiceError, language: AppLanguage) -> String {
        let locale = language.locale
        let name = error.provider.displayName
        let format: String
        switch error {
        case .missingKey:
            format = L10n.string( "Stel eerst je API-key voor %@ in bij Instellingen.", locale: locale)
        case .invalidKey:
            format = L10n.string( "De API-key voor %@ is ongeldig of geweigerd. Controleer de sleutel in Instellingen.", locale: locale)
        case .rateLimited:
            format = L10n.string( "%@ heeft tijdelijk te veel aanvragen. Probeer het over een moment opnieuw.", locale: locale)
        case .insufficientCredit:
            format = L10n.string( "%@ meldt onvoldoende tegoed of een factureringsprobleem. Controleer je provideraccount.", locale: locale)
        case .network:
            format = L10n.string( "Geen verbinding met %@. Controleer je internetverbinding.", locale: locale)
        case .timeout:
            format = L10n.string( "De aanvraag bij %@ duurde te lang. Probeer het opnieuw.", locale: locale)
        case .invalidResponse:
            format = L10n.string( "%@ gaf een onleesbaar antwoord. Probeer het opnieuw.", locale: locale)
        case .server(_, let detail):
            guard !detail.isEmpty else {
                return String(format: L10n.string( "Er ging iets mis bij %@.", locale: locale), locale: locale, name)
            }
            return String(
                format: L10n.string( "%1$@ gaf een fout: %2$@", locale: locale),
                locale: locale,
                name,
                detail
            )
        }
        return String(format: format, locale: locale, name)
    }

    private static func claudeMessage(_ error: ClaudeError, language: AppLanguage) -> String {
        let locale = language.locale
        switch error {
        case .missingKey:
            return L10n.string( "Stel eerst je Claude API-key in bij Instellingen.", locale: locale)
        case .invalidKey:
            return L10n.string( "Je Claude API-key is ongeldig of geweigerd. Controleer de sleutel in Instellingen.", locale: locale)
        case .overloaded:
            return L10n.string( "Claude is momenteel overbelast. Probeer het over een moment opnieuw.", locale: locale)
        case .network:
            return L10n.string( "Geen verbinding met Claude. Controleer je internetverbinding.", locale: locale)
        case .server(let detail):
            guard !detail.isEmpty else {
                return L10n.string( "Er ging iets mis bij het aanroepen van Claude.", locale: locale)
            }
            return String(format: L10n.string( "Claude gaf een fout: %@", locale: locale), locale: locale, detail)
        }
    }

    private static func parakeetMessage(_ error: ParakeetEngineError, language: AppLanguage) -> String {
        let locale = language.locale
        switch error {
        case .unsupportedHardware:
            return L10n.string( "Dit toestel ondersteunt het lokale spraakmodel niet.", locale: locale)
        case .noNetwork:
            return L10n.string( "Geen internetverbinding om het Parakeet-model te downloaden. Maak verbinding en probeer opnieuw.", locale: locale)
        case .downloadFailed(let detail):
            return String(format: L10n.string( "Het Parakeet-model kon niet worden gedownload: %@", locale: locale), locale: locale, detail)
        case .downloadStalled:
            return L10n.string( "Download lijkt vast te zitten — controleer je verbinding en probeer opnieuw.", locale: locale)
        case .modelNotLoaded:
            return L10n.string( "Het Parakeet-model is nog niet geladen.", locale: locale)
        case .notRecording:
            return L10n.string( "Er loopt geen opnamesessie.", locale: locale)
        case .transcriptionFailed(let detail):
            return String(format: L10n.string( "Transcriptie mislukte: %@", locale: locale), locale: locale, detail)
        }
    }

    private static func audioMessage(_ error: IOSAudioEngineError, language: AppLanguage) -> String {
        let locale = language.locale
        switch error {
        case .microphonePermissionDenied:
            return L10n.string( "Geen toegang tot de microfoon. Sta toegang toe in Instellingen › Privacy en beveiliging › Microfoon.", locale: locale)
        case .sessionConfigFailed(let detail):
            return String(format: L10n.string( "Audiosessie kon niet worden geconfigureerd: %@", locale: locale), locale: locale, detail)
        case .engineStartFailed(let detail):
            return String(format: L10n.string( "Microfoon kon niet starten: %@", locale: locale), locale: locale, detail)
        case .converterUnavailable:
            return L10n.string( "Audioformaat kon niet worden omgezet.", locale: locale)
        }
    }
}
