import Testing
import Foundation
@testable import Core

@Suite struct ExporterTests {

    private func entryWithSegments() -> TranscriptEntry {
        TranscriptEntry(
            id: "1",
            text: "Hallo wereld",
            createdAt: "2026-06-20T22:42:00+02:00",
            name: "Klantgesprek",
            segments: [
                TranscriptSegment(start: 0.0, end: 1.5, text: "Hallo"),
                TranscriptSegment(start: 1.5, end: 3.0, text: "wereld"),
            ]
        )
    }

    // MARK: - Ported from tests/test_exporter.py

    @Test func exportsUTF8TextAndAddsTxtSuffix() throws {
        let directory = try makeTempDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let path = try Exporter.exportText("Een Nederlandse transcriptie.", to: directory.appendingPathComponent("uitvoer"))

        #expect(path.pathExtension == "txt")
        let content = try String(contentsOf: path, encoding: .utf8)
        #expect(content == "Een Nederlandse transcriptie.\n")
    }

    @Test func suggestedNameUsesTranscriptionTimestamp() {
        let entry = TranscriptEntry(id: "1", text: "Tekst", createdAt: "2026-06-20T22:42:00+02:00")
        #expect(Exporter.suggestedExportName(for: entry) == "transcriptie-2026-06-20-2242.txt")
    }

    @Test func suggestedNameUsesNameAndExtension() {
        let entry = entryWithSegments()
        #expect(Exporter.suggestedExportName(for: entry, extension: "srt") == "Klantgesprek.srt")
    }

    @Test func srtExportHasNumberedCuesAndTimecodes() {
        let srt = Exporter.toSRT(entryWithSegments())
        #expect(srt.contains("00:00:00,000 --> 00:00:01,500"))
        #expect(srt.contains("Hallo"))
        #expect(srt.hasPrefix("1\n"))
    }

    @Test func vttExportStartsWithHeader() {
        let vtt = Exporter.toVTT(entryWithSegments())
        #expect(vtt.hasPrefix("WEBVTT"))
        #expect(vtt.contains("00:00:01.500 --> 00:00:03.000"))
    }

    @Test func markdownAndJSONExport() {
        let entry = entryWithSegments()
        #expect(Exporter.toMarkdown(entry).contains("# Klantgesprek"))
        #expect(Exporter.toJSON(entry).contains("\"text\": \"Hallo wereld\""))
    }

    @Test func exportEntryPicksWriterBySuffix() throws {
        let directory = try makeTempDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let path = try Exporter.exportEntry(entryWithSegments(), to: directory.appendingPathComponent("out.srt"))
        #expect(path.pathExtension == "srt")
        let content = try String(contentsOf: path, encoding: .utf8)
        #expect(content.contains("-->"))
    }

    @Test func exportAllWritesOneFilePerEntry() throws {
        let directory = try makeTempDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let entries = [entryWithSegments(), entryWithSegments()]
        let paths = try Exporter.exportAll(entries, to: directory.appendingPathComponent("bundel"), extension: "md")
        #expect(paths.count == 2)
        for path in paths {
            #expect(FileManager.default.fileExists(atPath: path.path))
            #expect(path.pathExtension == "md")
        }
    }

    // MARK: - Golden byte-equality (generated by the real Python code)

    private func multiSegmentEntry() -> TranscriptEntry {
        TranscriptEntry(
            id: "entry-multi-1",
            text: "Hallo wereld. Dit is een test transcriptie met meerdere segmenten.",
            createdAt: "2026-06-20T22:42:00+02:00",
            name: "Klantgesprek",
            pinned: true,
            language: "nl",
            model: "medium",
            source: "mic",
            duration: 3.0,
            segments: [
                TranscriptSegment(start: 0.0, end: 1.5, text: "Hallo wereld."),
                TranscriptSegment(start: 1.5, end: 3.0, text: "Dit is een test transcriptie met meerdere segmenten."),
            ]
        )
    }

    private func segmentlessEntry() -> TranscriptEntry {
        TranscriptEntry(
            id: "entry-nosegs-2",
            text: "Een transcriptie zonder segmenten, maar met wat tekst erin.",
            createdAt: "2026-06-20T09:15:30+02:00",
            name: "",
            pinned: false,
            language: "nl",
            model: "small",
            source: "mic",
            duration: 0.0,
            segments: []
        )
    }

    private func assertByteIdentical(_ produced: String, golden fileName: String, sourceLocation: SourceLocation = #_sourceLocation) throws {
        let url = try Fixtures.golden(fileName)
        let expectedData = try Data(contentsOf: url)
        let expected = String(decoding: expectedData, as: UTF8.self)
        #expect(produced == expected, "byte mismatch against golden file \(fileName)", sourceLocation: sourceLocation)
        // Belt-and-suspenders: also compare raw UTF-8 bytes directly.
        #expect(Array(produced.utf8) == Array(expectedData), "raw byte mismatch against golden file \(fileName)", sourceLocation: sourceLocation)
    }

    @Test func goldenTxtMultiSegment() throws {
        try assertByteIdentical(Exporter.toText(multiSegmentEntry()), golden: "multi_segment.txt")
    }

    @Test func goldenTxtSegmentless() throws {
        try assertByteIdentical(Exporter.toText(segmentlessEntry()), golden: "segmentless.txt")
    }

    @Test func goldenMarkdownMultiSegment() throws {
        try assertByteIdentical(Exporter.toMarkdown(multiSegmentEntry()), golden: "multi_segment.md")
    }

    @Test func goldenMarkdownSegmentless() throws {
        try assertByteIdentical(Exporter.toMarkdown(segmentlessEntry()), golden: "segmentless.md")
    }

    @Test func goldenSRTMultiSegment() throws {
        try assertByteIdentical(Exporter.toSRT(multiSegmentEntry()), golden: "multi_segment.srt")
    }

    @Test func goldenSRTSegmentless() throws {
        try assertByteIdentical(Exporter.toSRT(segmentlessEntry()), golden: "segmentless.srt")
    }

    @Test func goldenVTTMultiSegment() throws {
        try assertByteIdentical(Exporter.toVTT(multiSegmentEntry()), golden: "multi_segment.vtt")
    }

    @Test func goldenVTTSegmentless() throws {
        try assertByteIdentical(Exporter.toVTT(segmentlessEntry()), golden: "segmentless.vtt")
    }

    /// JSON is compared for byte-parity here; the hand-rolled encoder in
    /// `Exporter.toJSON` matches `json.dumps(..., ensure_ascii=False,
    /// indent=2)` exactly for the value shapes this app produces (strings,
    /// plain floats, arrays of segment objects), so full byte parity is
    /// achieved rather than falling back to semantic-only comparison.
    @Test func goldenJSONMultiSegment() throws {
        try assertByteIdentical(Exporter.toJSON(multiSegmentEntry()), golden: "multi_segment.json")
    }

    @Test func goldenJSONSegmentless() throws {
        try assertByteIdentical(Exporter.toJSON(segmentlessEntry()), golden: "segmentless.json")
    }

    @Test func goldenSuggestedNames() throws {
        let url = try Fixtures.golden("suggested_names.json")
        let data = try Data(contentsOf: url)
        let names = try JSONDecoder().decode([String: String].self, from: data)

        #expect(Exporter.suggestedExportName(for: segmentlessEntry(), extension: "txt") == names["no_name_uses_timestamp"])
        #expect(Exporter.suggestedExportName(for: multiSegmentEntry(), extension: "srt") == names["with_name_uses_slug"])

        let specialNameEntry = TranscriptEntry(
            id: "entry-special",
            text: "Iets",
            createdAt: "2026-01-05T08:00:00+01:00",
            name: "  Klant #1 (versie 2)!! "
        )
        #expect(Exporter.suggestedExportName(for: specialNameEntry, extension: "md") == names["special_chars_slugified"])
    }

    @Test func goldenExportAllNames() throws {
        let url = try Fixtures.golden("export_all_names.json")
        let data = try Data(contentsOf: url)
        let expectedNames = try JSONDecoder().decode([String].self, from: data)

        let specialNameEntry = TranscriptEntry(
            id: "entry-special",
            text: "Iets",
            createdAt: "2026-01-05T08:00:00+01:00",
            name: "  Klant #1 (versie 2)!! "
        )

        let directory = try makeTempDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        let paths = try Exporter.exportAll(
            [multiSegmentEntry(), segmentlessEntry(), specialNameEntry],
            to: directory.appendingPathComponent("bundel"),
            extension: "md"
        )
        #expect(paths.map(\.lastPathComponent) == expectedNames)
    }

    // MARK: - Helpers

    private func makeTempDirectory() throws -> URL {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        return url
    }
}
