import Testing
import Foundation
@testable import Core

@Suite struct TextProcessorTests {

    // MARK: - Ported from tests/test_textproc.py

    @Test func replacementsAreWholeWordAndCaseInsensitive() {
        let text = "Ik gebruik VPS en vps, maar niet vpsx."
        let result = TextProcessor.applyReplacements(text, [Replacement(find: "vps", replace: "server")])
        #expect(result == "Ik gebruik server en server, maar niet vpsx.")
    }

    @Test func replacementSkipsEmptyFind() {
        #expect(TextProcessor.applyReplacements("blijft", [Replacement(find: "", replace: "x")]) == "blijft")
    }

    /// The exact personal-woordenlijst examples from the UI empty-state.
    @Test func personalDictionaryExamples() {
        // "klot" (whatever the recognizer hears) → "Claude", case-insensitive.
        #expect(
            TextProcessor.applyReplacements("vraag het aan klot en Klot",
                                            [Replacement(find: "klot", replace: "Claude")])
                == "vraag het aan Claude en Claude"
        )
        // A hyphenated find like "G-A-X" → "GHX" (word boundaries surround it).
        #expect(
            TextProcessor.applyReplacements("we werken bij G-A-X vandaag.",
                                            [Replacement(find: "G-A-X", replace: "GHX")])
                == "we werken bij GHX vandaag."
        )
    }

    @Test func cleanCollapsesWhitespaceAndCapitalizesSentences() {
        let text = "  hallo   wereld .  dit is  een test.nieuwe zin "
        let result = TextProcessor.cleanText(text)
        #expect(result == "Hallo wereld. Dit is een test. Nieuwe zin")
    }

    @Test func cleanKeepsEmptyEmpty() {
        #expect(TextProcessor.cleanText("    ") == "")
    }

    @Test func processAppliesReplacementsThenCleanup() {
        let result = TextProcessor.process(
            "de klant heet  noornano .",
            replacements: [Replacement(find: "noornano", replace: "Noornano")],
            clean: true
        )
        #expect(result == "De klant heet Noornano.")
    }

    @Test func processCanSkipCleanup() {
        #expect(TextProcessor.process("rauw   blijft", clean: false) == "rauw   blijft")
    }

    // MARK: - Golden fixture equality (generated by the real Python code)

    private struct TextCase: Decodable {
        let id: String
        let input: String
        let replacements: [[String]]
        let clean: Bool
        let output: String
    }

    @Test func goldenTextProcessingCases() throws {
        let url = try Fixtures.golden("textproc_cases.json")
        let data = try Data(contentsOf: url)
        let cases = try JSONDecoder().decode([TextCase].self, from: data)
        #expect(!cases.isEmpty, "golden fixture should not be empty")

        for testCase in cases {
            let replacements = testCase.replacements.map { pair in
                Replacement(find: pair[0], replace: pair[1])
            }
            let result = TextProcessor.process(testCase.input, replacements: replacements, clean: testCase.clean)
            let message = "golden case '\(testCase.id)' mismatched. input=\(testCase.input.debugDescription)"
            #expect(result == testCase.output, Comment(rawValue: message))
        }
    }

    // MARK: - Additional edge cases (defensive, not from golden set)

    @Test func digitExceptionKeepsDecimalIntact() {
        // The digit lookahead exception should prevent inserting a space
        // between "1" and "5" in "1.5".
        let result = TextProcessor.cleanText("de prijs is 1.5 euro")
        #expect(result.contains("1.5"), "expected '1.5' to remain intact, got: \(result)")
    }

    @Test func literalReplacementDoesNotExpandBackreferenceSyntax() {
        // Replacement strings containing regex-template-like syntax must
        // be inserted literally, not interpreted as backreferences.
        let result = TextProcessor.applyReplacements("foo", [Replacement(find: "foo", replace: "$1 and \\1")])
        #expect(result == "$1 and \\1")
    }

    // MARK: - Filler-word removal (M7)

    /// The headline case from the spec: hesitation sounds are stripped and the
    /// resulting extra spaces collapse cleanly.
    @Test func removeFillersStripsDutchHesitationSounds() {
        let result = TextProcessor.removeFillers("Dit is eh een test met uh stopwoorden", language: "nl")
        #expect(result == "Dit is een test met stopwoorden")
    }

    /// Matching is case-insensitive and covers the ehm/uhm variants.
    @Test func removeFillersIsCaseInsensitive() {
        let result = TextProcessor.removeFillers("Ehm dit is UHM prima", language: "nl")
        #expect(result == "dit is prima")
    }

    /// A filler right before a comma must not leave a dangling " ," seam.
    @Test func removeFillersFixesPunctuationSpacing() {
        let result = TextProcessor.removeFillers("Nou eh, dat klopt", language: "nl")
        #expect(result == "Nou, dat klopt")
    }

    /// A sentence-INITIAL filler must not leave a stray leading . ! ? , ; :
    @Test func removeFillersStripsLeadingOrphanPunctuation() {
        #expect(TextProcessor.removeFillers("eh. Dit is een test", fillers: ["eh"]) == "Dit is een test")
        #expect(TextProcessor.removeFillers("uh! Kijk daar", fillers: ["uh"]) == "Kijk daar")
        #expect(TextProcessor.removeFillers("ehm, dus we gaan", fillers: ["ehm"]) == "dus we gaan")
    }

    /// Meaningful words that merely resemble fillers (or that were explicitly
    /// excluded from the conservative list) are kept.
    @Test func removeFillersKeepsMeaningfulWords() {
        // "eigenlijk", "gewoon", "nou", "ja" are intentionally NOT fillers.
        let text = "Ik ga eigenlijk gewoon door, nou ja."
        #expect(TextProcessor.removeFillers(text, language: "nl") == text)
        // Whole-word only: "uhr" / "ehandel" contain filler letters but are words.
        #expect(TextProcessor.removeFillers("de uhrwerk staat", language: "nl") == "de uhrwerk staat")
    }

    /// Multi-word fillers are removed as a phrase, not leaving a component word.
    @Test func removeFillersHandlesMultiWordFillers() {
        let result = TextProcessor.removeFillers("Dat is zeg maar prima", language: "nl")
        #expect(result == "Dat is prima")
    }

    /// Custom list overload removes exactly what it is given and nothing more.
    @Test func removeFillersWithExplicitListIsExact() {
        let result = TextProcessor.removeFillers("keep drop keep", fillers: ["drop"])
        #expect(result == "keep keep")
    }

    /// An empty filler list is a no-op.
    @Test func removeFillersEmptyListIsNoOp() {
        #expect(TextProcessor.removeFillers("niks verandert hier", fillers: []) == "niks verandert hier")
    }

    /// `process` only strips fillers when the flag is set, and leaves output
    /// untouched otherwise (respecting the flag).
    @Test func processRespectsRemoveFillersFlag() {
        let input = "Dit is eh een test met uh stopwoorden"
        // Flag off: fillers stay (cleanText still capitalizes/normalizes).
        let off = TextProcessor.process(input, clean: true, removeFillers: false)
        #expect(off.contains(" eh ") && off.contains(" uh "))
        // Flag on: fillers gone, sentence cleaned + capitalized.
        let on = TextProcessor.process(input, clean: true, removeFillers: true, language: "nl")
        #expect(on == "Dit is een test met stopwoorden")
    }

    /// English gets its extra bare hesitation tokens ("er"), which are gated off
    /// for Dutch to avoid clobbering meaning.
    @Test func removeFillersEnglishListAddsBareTokens() {
        #expect(TextProcessor.removeFillers("this is er fine", language: "en") == "this is fine")
        // Dutch must NOT strip a bare "er" (a real, meaningful Dutch word).
        #expect(TextProcessor.removeFillers("er staat een er", language: "nl") == "er staat een er")
    }
}
