import Testing
import Foundation
@testable import Core

@Suite struct TextProcessorTests {

    // MARK: - Ported from tests/test_textproc.py

    @Test func replacementsAreWholeWordAndCaseInsensitive() {
        let text = "Ik gebruik VPS en vps, maar niet vpsx."
        let result = TextProcessor.applyReplacements(text, [Replacement(find: "vps", replace: "server")])
        #expect(result == "Ik gebruik server en server, maar niet vpsx.")
    }

    @Test func replacementSkipsEmptyFind() {
        #expect(TextProcessor.applyReplacements("blijft", [Replacement(find: "", replace: "x")]) == "blijft")
    }

    @Test func cleanCollapsesWhitespaceAndCapitalizesSentences() {
        let text = "  hallo   wereld .  dit is  een test.nieuwe zin "
        let result = TextProcessor.cleanText(text)
        #expect(result == "Hallo wereld. Dit is een test. Nieuwe zin")
    }

    @Test func cleanKeepsEmptyEmpty() {
        #expect(TextProcessor.cleanText("    ") == "")
    }

    @Test func processAppliesReplacementsThenCleanup() {
        let result = TextProcessor.process(
            "de klant heet  noornano .",
            replacements: [Replacement(find: "noornano", replace: "Noornano")],
            clean: true
        )
        #expect(result == "De klant heet Noornano.")
    }

    @Test func processCanSkipCleanup() {
        #expect(TextProcessor.process("rauw   blijft", clean: false) == "rauw   blijft")
    }

    // MARK: - Golden fixture equality (generated by the real Python code)

    private struct TextCase: Decodable {
        let id: String
        let input: String
        let replacements: [[String]]
        let clean: Bool
        let output: String
    }

    @Test func goldenTextProcessingCases() throws {
        let url = try Fixtures.golden("textproc_cases.json")
        let data = try Data(contentsOf: url)
        let cases = try JSONDecoder().decode([TextCase].self, from: data)
        #expect(!cases.isEmpty, "golden fixture should not be empty")

        for testCase in cases {
            let replacements = testCase.replacements.map { pair in
                Replacement(find: pair[0], replace: pair[1])
            }
            let result = TextProcessor.process(testCase.input, replacements: replacements, clean: testCase.clean)
            let message = "golden case '\(testCase.id)' mismatched. input=\(testCase.input.debugDescription)"
            #expect(result == testCase.output, Comment(rawValue: message))
        }
    }

    // MARK: - Additional edge cases (defensive, not from golden set)

    @Test func digitExceptionKeepsDecimalIntact() {
        // The digit lookahead exception should prevent inserting a space
        // between "1" and "5" in "1.5".
        let result = TextProcessor.cleanText("de prijs is 1.5 euro")
        #expect(result.contains("1.5"), "expected '1.5' to remain intact, got: \(result)")
    }

    @Test func literalReplacementDoesNotExpandBackreferenceSyntax() {
        // Replacement strings containing regex-template-like syntax must
        // be inserted literally, not interpreted as backreferences.
        let result = TextProcessor.applyReplacements("foo", [Replacement(find: "foo", replace: "$1 and \\1")])
        #expect(result == "$1 and \\1")
    }
}
